meta_product_name: "CherryPickr"
meta_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "cherry.png" # should exist in `app/assets/images/`  # required for Twitter Cards
