meta_product_name: "CherryPickr"
meta_title: "CherryPickr - Bringing you the cheapest prices"
meta_description: "Cheapest prices for everyday products"
meta_image: "cherry.png" # should exist in `app/assets/images/`  # required for Twitter Cards
